version: '3'

services:
  db:
    image: postgres:latest
    ports:
      - "5435:5432"
    volumes:
      - local_db_data:/var/lib/postgresql/data
    env_file:
      - ./deploy/db/.env

  backend:
    build:
      context: .
      dockerfile: ./deploy/backend/Dockerfile
    depends_on:
      - db
    volumes:
      - ./backend:/app/backend
      - ./static:/app/static
    env_file:
      - ./deploy/backend/.env
      - ./deploy/db/.env
    ports:
      - "5000:5000"

  frontend:
    build:
      context: .
      dockerfile: ./deploy/frontend/Dockerfile
    depends_on:
      - backend
    volumes:
      - ./frontend:/app/frontend
      - ./static:/app/static
    ports:
      - "8080:8080"

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./deploy/rabbitmq:/etc/rabbitmq

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: deploy/celery/Dockerfile
    env_file:
      - deploy/backend/.env
    depends_on:
      - rabbitmq
      - redis
    volumes:
      - ./backend:/app/backend


volumes:
  local_db_data: { }
