version: '3'

volumes:
  local_db_data: {}
  local_db_data_backups: {}
  app_data: {}

networks:
  geo_net:
    ipam:
      config:
        - subnet: "10.0.12.1/24"

services:
  db:
    image: postgres:latest
    networks:
      geo_net:
        ipv4_address: 10.0.12.2
    volumes:
      - local_db_data:/var/lib/postgresql/data
      - local_db_data_backups:/backups
    env_file:
      - ./deploy/db/.env

  backend:
    build:
      context: .
      dockerfile: ./deploy/backend/Dockerfile
    networks:
      geo_net:
        ipv4_address: 10.0.12.3
    volumes:
      - ./backend:/app/backend
      - app_data:/data
    env_file:
      - ./deploy/backend/.env
      - ./deploy/db/.env
      - ./deploy/shared.env
    depends_on:
      - db
      - celery

  frontend:
    build:
      context: .
      dockerfile: ./deploy/frontend/Dockerfile
    networks:
      geo_net:
        ipv4_address: 10.0.12.4
    volumes:
      - ./frontend:/app/frontend
      - app_data:/data
    environment:
      API_HOST: "http://10.0.12.12"
    env_file:
      - ./deploy/shared.env
    depends_on:
      - backend
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:management-alpine
    networks:
      geo_net:
        ipv4_address: 10.0.12.5
    volumes:
      - app_data:/data
      - ./deploy/rabbitmq/config:/etc/rabbitmq
    env_file:
      - ./deploy/rabbitmq/.env

  redis:
    image: redis:alpine
    networks:
      geo_net:
        ipv4_address: 10.0.12.6
    volumes:
      - app_data:/data

  celery:
    build:
      context: .
      dockerfile: ./deploy/celery/Dockerfile
    networks:
      geo_net:
        ipv4_address: 10.0.12.7
    volumes:
      - app_data:/data
      - ./backend:/app/backend
    env_file:
      - ./deploy/rabbitmq/.env
      - ./deploy/backend/.env
      - ./deploy/shared.env
    depends_on:
      - rabbitmq
      - redis

  flower:
    build:
      context: .
      dockerfile: ./deploy/flower/Dockerfile
    networks:
      geo_net:
        ipv4_address: 10.0.12.8
    volumes:
      - app_data:/data
      - ./backend:/app/backend
      - ./deploy/flower/config:/config
    env_file:
      - ./deploy/rabbitmq/.env
      - ./deploy/backend/.env
      - ./deploy/shared.env
    depends_on:
      - celery

  lb:
    build:
      context: .
      dockerfile: ./deploy/lb/Dockerfile
    networks:
      geo_net:
        ipv4_address: 10.0.12.12
    depends_on:
      - backend
      - frontend
      - celery

