version: '3'

volumes:
  local_db_data: {}
  local_db_data_backups: {}

services:
  backend:
    build:
      context: .
      dockerfile: ./deploy/backend/Dockerfile
    depends_on:
      - db
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
      - ./static:/app/static
    env_file:
      - ./deploy/backend/.env
      - ./deploy/db/.env
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: ./deploy/frontend/Dockerfile
    depends_on:
      - backend
    volumes:
      - ./frontend:/app/frontend
      - ./static:/app/static
    ports:
      - "8080:8080"

  db:
    image: postgres:latest
    ports:
      - "5435:5432"
    volumes:
      - local_db_data:/var/lib/postgresql/data
      - local_db_data_backups:/backups
    env_file:
      - ./deploy/db/.env
