#!/bin/sh

export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DATABASE_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

echo "Waiting for postgres..."

while ! pg_isready -d "$DATABASE_URL" > /dev/null 2> /dev/null; do
    isready=$(pg_isready -d "$DATABASE_URL");
    echo "$isready"
    sleep 1
done

echo "PostgreSQL started"

flask db upgrade

exec "$@"
