"""empty message

Revision ID: 083a525413fd
Revises: 0860d9bafd8b
Create Date: 2022-05-20 13:01:00.212241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '083a525413fd'
down_revision = '0860d9bafd8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_field', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_field', 'order')
    # ### end Alembic commands ###
