"""empty message

Revision ID: 0860d9bafd8b
Revises: b8ae3b6cfcea
Create Date: 2022-05-20 12:22:31.036604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0860d9bafd8b'
down_revision = 'b8ae3b6cfcea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_name'), 'form', ['name'], unique=True)
    op.create_table('form_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_json', sa.JSON(), nullable=True),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['form.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form_field')
    op.drop_index(op.f('ix_form_name'), table_name='form')
    op.drop_table('form')
    # ### end Alembic commands ###
