"""empty message

Revision ID: 1d07080df41a
Revises: f1c0b8e8d1c3
Create Date: 2022-05-26 22:13:55.686328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d07080df41a'
down_revision = 'f1c0b8e8d1c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('twitter', sa.String(length=50), nullable=True),
    sa.Column('github', sa.String(length=50), nullable=True),
    sa.Column('links', sa.JSON(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('blog_post',
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['blog_author.id'], ),
    sa.PrimaryKeyConstraint('slug'),
    sa.UniqueConstraint('slug')
    )
    op.add_column('user', sa.Column('pronouns', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'pronouns')
    op.drop_table('blog_post')
    op.drop_table('blog_author')
    # ### end Alembic commands ###
