"""empty message

Revision ID: 3ffd277e8683
Revises: 970716cff586
Create Date: 2021-10-08 15:04:44.713541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ffd277e8683'
down_revision = '970716cff586'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_analyses',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis.id'], ),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.PrimaryKeyConstraint('application_id', 'analysis_id')
    )
    op.add_column('application', sa.Column('date_from', sa.Date(), nullable=True))
    op.add_column('application', sa.Column('date_to', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'date_to')
    op.drop_column('application', 'date_from')
    op.drop_table('application_analyses')
    # ### end Alembic commands ###
