"""empty message

Revision ID: 63bb1f5f1788
Revises: c5ec23ac5a83
Create Date: 2021-10-11 10:53:37.096688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63bb1f5f1788'
down_revision = 'c5ec23ac5a83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('about_you', sa.String(), nullable=True))
    op.add_column('application', sa.Column('days_estimate', sa.Integer(), nullable=True))
    op.add_column('application', sa.Column('samples_estimate', sa.Integer(), nullable=True))
    op.add_column('application', sa.Column('need_to_visit', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('application', sa.Column('prep_required', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('application', sa.Column('other_analyses', sa.String(), nullable=True))
    op.alter_column('application', 'date_from',
               existing_type=sa.DATE(),
               nullable=False, server_default=sa.func.now())
    op.drop_column('application', 'able_to_travel')
    op.add_column('facility', sa.Column('other_analyses', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facility', 'other_analyses')
    op.add_column('application', sa.Column('able_to_travel', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('application', 'date_from',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('application', 'other_analyses')
    op.drop_column('application', 'prep_required')
    op.drop_column('application', 'need_to_visit')
    op.drop_column('application', 'samples_estimate')
    op.drop_column('application', 'days_estimate')
    op.drop_column('application', 'about_you')
    # ### end Alembic commands ###
