"""empty message

Revision ID: 7059351a7931
Revises: dfc1c2f08bec
Create Date: 2022-06-05 13:56:15.245745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7059351a7931'
down_revision = 'dfc1c2f08bec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('family_name', sa.String(length=100), nullable=False, server_default='x'))
    op.add_column('user', sa.Column('given_name', sa.String(length=100), nullable=False, server_default='y'))
    op.add_column('user', sa.Column('given_name_first', sa.Boolean(), nullable=True))
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('user', 'given_name_first')
    op.drop_column('user', 'given_name')
    op.drop_column('user', 'family_name')
    # ### end Alembic commands ###
