"""empty message

Revision ID: 7ac43c651387
Revises: 3ffd277e8683
Create Date: 2021-10-08 15:41:38.647802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ac43c651387'
down_revision = '3ffd277e8683'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['slot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('application', sa.Column('date_submitted', sa.Date(), nullable=True))
    op.add_column('application', sa.Column('is_submitted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'is_submitted')
    op.drop_column('application', 'date_submitted')
    op.drop_table('offer')
    # ### end Alembic commands ###
