"""empty message

Revision ID: a42ac112a46d
Revises: 083a525413fd
Create Date: 2022-05-26 07:53:01.437568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a42ac112a46d'
down_revision = '083a525413fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_field', sa.Column('name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_field', 'name')
    # ### end Alembic commands ###
