"""empty message

Revision ID: a8501b4899d2
Revises: 63bb1f5f1788
Create Date: 2021-10-12 09:43:53.360067

"""
import enum

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
from backend.geocolab.models.info import funding_level, access_type

# revision identifiers, used by Alembic.
revision = 'a8501b4899d2'
down_revision = '63bb1f5f1788'
branch_labels = None
depends_on = None



def upgrade():
    access_type_enum = postgresql.ENUM(*access_type.keys(), name='access_type')
    access_type_enum.create(op.get_bind(), checkfirst=True)
    funding_level_enum = postgresql.ENUM(*funding_level.keys(), name='funding_level')
    funding_level_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('access_type', access_type_enum, nullable=False, server_default='any'))
    op.add_column('application',
                  sa.Column('funding_level', funding_level_enum, nullable=False, server_default='none'))
    op.drop_column('application', 'need_to_visit')
    op.drop_column('application', 'fund_own_travel')
    op.add_column('org', sa.Column('funding_limit', sa.Integer(), nullable=True))
    op.add_column('org', sa.Column('funding_level', funding_level_enum, nullable=False, server_default='none'))
    op.add_column('org', sa.Column('accepted_access_types', access_type_enum, nullable=False, server_default='any'))
    op.drop_column('org', 'will_fund_travel')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('org', sa.Column('will_fund_travel', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('org', 'accepted_access_types')
    op.drop_column('org', 'funding_level')
    op.drop_column('org', 'funding_limit')
    op.add_column('application', sa.Column('fund_own_travel', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('application',
                  sa.Column('need_to_visit', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False,
                            nullable=False))
    op.drop_column('application', 'funding_level')
    op.drop_column('application', 'access_type')
    # ### end Alembic commands ###
