"""empty message

Revision ID: d44947b2f0c5
Revises: f2e98d3344e6
Create Date: 2022-05-26 14:43:32.521067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd44947b2f0c5'
down_revision = 'f2e98d3344e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edi_extra_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_type', sa.String(length=50), nullable=True),
    sa.Column('role_type_expand', sa.String(), nullable=True),
    sa.Column('career_stage', sa.String(length=50), nullable=True),
    sa.Column('contract', sa.String(length=50), nullable=True),
    sa.Column('funding', sa.String(length=50), nullable=True),
    sa.Column('funding_expand', sa.String(), nullable=True),
    sa.Column('has_budget', sa.Boolean(), nullable=True),
    sa.Column('budget_value', sa.Integer(), nullable=True),
    sa.Column('budget_currency', sa.String(), nullable=True),
    sa.Column('family_first_bachelors', sa.Boolean(), nullable=True),
    sa.Column('family_first_masters', sa.Boolean(), nullable=True),
    sa.Column('family_first_phd', sa.Boolean(), nullable=True),
    sa.Column('family_first_academic', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['form.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('edi_extra_data')
    # ### end Alembic commands ###
