"""empty message

Revision ID: f1c0b8e8d1c3
Revises: d44947b2f0c5
Create Date: 2022-05-26 20:15:29.096730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1c0b8e8d1c3'
down_revision = 'd44947b2f0c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('edi_extra_data', sa.Column('family_firsts', sa.JSON(), nullable=True))
    op.drop_column('edi_extra_data', 'family_first_academic')
    op.drop_column('edi_extra_data', 'family_first_phd')
    op.drop_column('edi_extra_data', 'family_first_masters')
    op.drop_column('edi_extra_data', 'family_first_bachelors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('edi_extra_data', sa.Column('family_first_bachelors', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('edi_extra_data', sa.Column('family_first_masters', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('edi_extra_data', sa.Column('family_first_phd', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('edi_extra_data', sa.Column('family_first_academic', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('edi_extra_data', 'family_firsts')
    # ### end Alembic commands ###
